---
title: Wales beats Turkey, Russia beats Finland
author: HS
date: '2021-06-16'
slug: wales-beats-turkey-russia-beats-finland
categories:
  - Game
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2021-06-16T20:47:25+02:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---


```{r init, echo=FALSE, message=FALSE , warning=FALSE}

library(tidyverse)
library(igraph)
library(readxl)
library(knitr)

knitr::opts_chunk$set(out.width = "100%")

```

Fairly anticipated outcomes so far today. Ida and Jacob fell a few spots as the rest roared on. Scott gained two points on Sebastian, but the leaderboard remain quite a lot like yesterday's. Maybe the 9pm game can cause some more stir in our standings.

```{r graph, echo = FALSE, warning=FALSE,  fig.height=10, fig.width=10}

nettverk <- read.csv("res14.csv", sep = ";", header = FALSE )

leaderboard <- tibble::as_tibble(nettverk)

leaderboard <- leaderboard %>% arrange_at(ncol(.), desc)

hbar<-leaderboard 
hbar$diff<-hbar$V14-hbar$V13

ggplot(hbar, aes(x=reorder(V1, V14), y=V14, fill = diff )) + 
    geom_bar(stat = 'identity') + 
    scale_y_continuous(limits = c(0, 275)) +
    coord_flip() + 
    scale_fill_gradient2(low = "red", high="blue") +
    geom_text(aes(label = V14), hjust=-0.75, size = 5 ) + 
    ylab("Points") +
    xlab(" ") +
    theme(axis.text=element_text(size=18), axis.title=element_text(size=18,face="bold"))

```