---
title: Almost there
author: HS
date: '2021-06-23'
slug: almost-there
categories:
  - Game
tags:
  - Euro2021
subtitle: ''
summary: ''
authors: []
lastmod: '2021-06-23T22:24:15+02:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---



```{r init, echo=FALSE, message=FALSE , warning=FALSE}

library(tidyverse)
library(igraph)
library(readxl)
library(knitr)

knitr::opts_chunk$set(out.width = "100%")

```

Sweden is Group E winners,  Forsberg was briefly joint top scorer. 

Spain's 5-0 victory was unpredicted, except for Jonas, Tor and Øivind, and the duo in the lead, where Sebastian has extended his lead to 16 points.

```{r graph, echo = FALSE, warning=FALSE,  fig.height=10, fig.width=10}

nettverk <- read.csv("res34.csv", sep = ";", header = FALSE )

leaderboard <- tibble::as_tibble(nettverk)

leaderboard <- leaderboard %>% arrange_at(ncol(.), desc)

hbar<-leaderboard 
hbar$diff<-hbar$V35-hbar$V33

ggplot(hbar, aes(x=reorder(V1, V35), y=V35, fill = diff )) + 
    geom_bar(stat = 'identity') + 
    scale_y_continuous(limits = c(-5, 645)) +
    coord_flip() + 
    scale_fill_gradient2(low = "red", high="blue") +
    geom_text(aes(label = V35), hjust=-0.75, size = 5 ) + 
    ylab("Points") +
    xlab(" ") +
    theme(axis.text=element_text(size=18), axis.title=element_text(size=18,face="bold"))

```